import type { Cliente } from './tipos'

/* ==========================================================================
   A porta de entrada do dado de cliente.

   Hoje ela devolve uma lista de exemplo guardada aqui. Quando o Supabase
   entrar (passo 7) e a base do Bling for importada (passo 11), so este arquivo
   muda: a tela, os filtros e a ficha continuam iguais, porque conversam com
   estas funcoes e nao com o banco.

   ATENCAO: os clientes abaixo sao inventados. Nenhum nome, documento ou
   telefone aqui pertence a alguem de verdade. Eles existem para a tela poder
   ser vista e conferida antes de haver dado real.
   ========================================================================== */

const EXEMPLO: Cliente[] = [
    {
      "id": "C0001",
      "nome": "CrossBox Delta",
      "fantasia": "",
      "tipo": "J",
      "documento": "33218196001338",
      "contato": "Diego",
      "telefone": "",
      "celular": "62904344257",
      "email": "delta@exemplo.com.br",
      "endereco": "Avenida Independência, 1760",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38452601",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "academia",
      "vendedor": "Marcela",
      "pedidos": 14,
      "total": 66280,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2024-04-24"
    },
    {
      "id": "C0002",
      "nome": "Escola Girassol",
      "fantasia": "",
      "tipo": "J",
      "documento": "65423511615594",
      "contato": "Paulo",
      "telefone": "6232265250",
      "celular": "62975279785",
      "email": "girassol@exemplo.com.br",
      "endereco": "Rua João Pessoa, 78",
      "complemento": "Quadra 29 lote 2",
      "bairro": "Cidade Jardim",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74815908",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Rafael",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-07-17"
    },
    {
      "id": "C0003",
      "nome": "Igreja Rio Claro",
      "fantasia": "",
      "tipo": "J",
      "documento": "10341316475255",
      "contato": "Renata",
      "telefone": "",
      "celular": "62943742169",
      "email": "rioclaro@exemplo.com.br",
      "endereco": "Rua 15, 1716",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75830166",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 8,
      "total": 37170,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2025-04-17"
    },
    {
      "id": "C0004",
      "nome": "Transportes São Jorge",
      "fantasia": "TRANSPORTES GROUP",
      "tipo": "J",
      "documento": "03056413953767",
      "contato": "Vitor",
      "telefone": "",
      "celular": "62943393287",
      "email": "saojorge@exemplo.com.br",
      "endereco": "Rua das Acácias, 675",
      "complemento": "Quadra 3 lote 11",
      "bairro": "Centro",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75013186",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 5295,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2025-03-11"
    },
    {
      "id": "C0005",
      "nome": "Corrida Anhanguera",
      "fantasia": "CORRIDA EVENTOS",
      "tipo": "J",
      "documento": "28710122691669",
      "contato": "Aline",
      "telefone": "",
      "celular": "62986695119",
      "email": "anhanguera@exemplo.com.br",
      "endereco": "Avenida Contorno, 1867",
      "complemento": "Sala 27",
      "bairro": "Setor Marista",
      "cidade": "Jataí",
      "uf": "GO",
      "cep": "75800913",
      "tipoDeContato": "Cliente",
      "segmento": "evento",
      "vendedor": "Marcela",
      "pedidos": 6,
      "total": 35871,
      "ultimoPedido": "2026-09-09",
      "criadoEm": "2026-01-09"
    },
    {
      "id": "C0006",
      "nome": "Comunidade Vertex",
      "fantasia": "",
      "tipo": "J",
      "documento": "62704828148932",
      "contato": "Fernando",
      "telefone": "6234149610",
      "celular": "62926469837",
      "email": "vertex@exemplo.com.br",
      "endereco": "Rua Padre Wendel, 230",
      "complemento": "",
      "bairro": "Jardim América",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75269099",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Henrique",
      "pedidos": 19,
      "total": 120504,
      "ultimoPedido": "2026-09-09",
      "criadoEm": "2023-04-23"
    },
    {
      "id": "C0007",
      "nome": "Comunidade Guará",
      "fantasia": "",
      "tipo": "J",
      "documento": "30391171822782",
      "contato": "Vitor",
      "telefone": "",
      "celular": "62986457932",
      "email": "guará@exemplo.com.br",
      "endereco": "Avenida Goiás, 601",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75386030",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 6380,
      "ultimoPedido": "2025-11-06",
      "criadoEm": "2025-07-16"
    },
    {
      "id": "C0008",
      "nome": "Paróquia Pequi",
      "fantasia": "",
      "tipo": "J",
      "documento": "71331509839301",
      "contato": "Paulo",
      "telefone": "",
      "celular": "62937502104",
      "email": "pequi@exemplo.com.br",
      "endereco": "Rua 84, 1669",
      "complemento": "Sala 7",
      "bairro": "Setor Campinas",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74824628",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-10-24"
    },
    {
      "id": "C0009",
      "nome": "Cooperativa Cerrado",
      "fantasia": "",
      "tipo": "F",
      "documento": "99737631165",
      "contato": "Aline",
      "telefone": "",
      "celular": "62967358651",
      "email": "cerrado@exemplo.com.br",
      "endereco": "Avenida T-9, 164",
      "complemento": "Sala 3",
      "bairro": "Centro",
      "cidade": "Catalão",
      "uf": "GO",
      "cep": "75701948",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 27,
      "total": 140441,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2023-01-01"
    },
    {
      "id": "C0010",
      "nome": "Igreja Jacarandá",
      "fantasia": "",
      "tipo": "J",
      "documento": "33387262473178",
      "contato": "Renata",
      "telefone": "",
      "celular": "62908289856",
      "email": "jacarandá@exemplo.com.br",
      "endereco": "Avenida Goiás, 1113",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74821993",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 27,
      "total": 26650,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2025-05-04"
    },
    {
      "id": "C0011",
      "nome": "Tucano Construções",
      "fantasia": "",
      "tipo": "J",
      "documento": "02606474687234",
      "contato": "Marcela",
      "telefone": "",
      "celular": "62909589883",
      "email": "tucano@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1057",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75851819",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-11-27"
    },
    {
      "id": "C0012",
      "nome": "Time Aurora",
      "fantasia": "TIME SPORTS",
      "tipo": "J",
      "documento": "21913619399091",
      "contato": "Vitor",
      "telefone": "",
      "celular": "62995629565",
      "email": "aurora@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 453",
      "complemento": "Galpão 1",
      "bairro": "Parque Amazônia",
      "cidade": "Catalão",
      "uf": "GO",
      "cep": "75700937",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Marcela",
      "pedidos": 3,
      "total": 19244,
      "ultimoPedido": "2026-08-17",
      "criadoEm": "2022-11-29"
    },
    {
      "id": "C0013",
      "nome": "Festival Horizonte",
      "fantasia": "FESTIVAL EVENTOS",
      "tipo": "J",
      "documento": "47510799118384",
      "contato": "Eduardo",
      "telefone": "6238196369",
      "celular": "62957182127",
      "email": "horizonte@exemplo.com.br",
      "endereco": "Avenida Perimetral, 740",
      "complemento": "Galpão 4",
      "bairro": "Setor Oeste",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75086579",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "evento",
      "vendedor": "Marcela",
      "pedidos": 1,
      "total": 3080,
      "ultimoPedido": "2026-08-26",
      "criadoEm": "2024-03-17"
    },
    {
      "id": "C0014",
      "nome": "Instituto Educacional São Jorge",
      "fantasia": "",
      "tipo": "J",
      "documento": "12411824493534",
      "contato": "Eduardo",
      "telefone": "6239885919",
      "celular": "62980045114",
      "email": "saojorge@exemplo.com.br",
      "endereco": "Avenida Perimetral, 190",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71754323",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Henrique",
      "pedidos": 27,
      "total": 32392,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2024-04-16"
    },
    {
      "id": "C0015",
      "nome": "Igreja Girassol",
      "fantasia": "",
      "tipo": "J",
      "documento": "42786801128059",
      "contato": "Larissa",
      "telefone": "",
      "celular": "62924268041",
      "email": "girassol@exemplo.com.br",
      "endereco": "Rua 84, 351",
      "complemento": "",
      "bairro": "Jardim Goiás",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71194875",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 1146,
      "ultimoPedido": "2026-07-19",
      "criadoEm": "2026-06-11"
    },
    {
      "id": "C0016",
      "nome": "São Jorge Engenharia",
      "fantasia": "SÃO GROUP",
      "tipo": "J",
      "documento": "58692322602563",
      "contato": "Diego",
      "telefone": "",
      "celular": "62926082771",
      "email": "saojorge@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1525",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75387491",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 4,
      "total": 24183,
      "ultimoPedido": "2025-07-19",
      "criadoEm": "2024-01-11"
    },
    {
      "id": "C0017",
      "nome": "Igreja Araguaia",
      "fantasia": "",
      "tipo": "J",
      "documento": "30365414586850",
      "contato": "Paulo",
      "telefone": "",
      "celular": "62942793925",
      "email": "araguaia@exemplo.com.br",
      "endereco": "Avenida Contorno, 1279",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74818625",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 8,
      "total": 52631,
      "ultimoPedido": "2026-08-03",
      "criadoEm": "2026-06-14"
    },
    {
      "id": "C0018",
      "nome": "Paróquia Jatobá",
      "fantasia": "",
      "tipo": "J",
      "documento": "81693406088356",
      "contato": "Tatiane",
      "telefone": "",
      "celular": "62954096143",
      "email": "jatobá@exemplo.com.br",
      "endereco": "Avenida T-9, 55",
      "complemento": "",
      "bairro": "Cidade Jardim",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74827601",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 10,
      "total": 59032,
      "ultimoPedido": "2026-01-15",
      "criadoEm": "2024-12-24"
    },
    {
      "id": "C0019",
      "nome": "Paróquia Buriti",
      "fantasia": "",
      "tipo": "J",
      "documento": "48236629946804",
      "contato": "Bruno",
      "telefone": "",
      "celular": "62934438043",
      "email": "buriti@exemplo.com.br",
      "endereco": "Rua João Pessoa, 1205",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75388955",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Rafael",
      "pedidos": 19,
      "total": 82116,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2024-11-10"
    },
    {
      "id": "C0020",
      "nome": "Vale Verde Construções",
      "fantasia": "VALE GROUP",
      "tipo": "J",
      "documento": "21489513433200",
      "contato": "Diego",
      "telefone": "6237155578",
      "celular": "62977842193",
      "email": "valeverde@exemplo.com.br",
      "endereco": "Rua 15, 388",
      "complemento": "Galpão 1",
      "bairro": "Setor Sul",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75859797",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 5,
      "total": 16726,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2023-06-10"
    },
    {
      "id": "C0021",
      "nome": "Grupo Buriti",
      "fantasia": "",
      "tipo": "F",
      "documento": "01632870831",
      "contato": "Fernando",
      "telefone": "",
      "celular": "62921848612",
      "email": "buriti@exemplo.com.br",
      "endereco": "Rua João Pessoa, 271",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Jataí",
      "uf": "GO",
      "cep": "75801147",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 10,
      "total": 40336,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2023-04-30"
    },
    {
      "id": "C0022",
      "nome": "Festival Uirapuru",
      "fantasia": "",
      "tipo": "J",
      "documento": "72774348734714",
      "contato": "Renata",
      "telefone": "",
      "celular": "62944516502",
      "email": "uirapuru@exemplo.com.br",
      "endereco": "Rua 15, 1815",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75810497",
      "tipoDeContato": "Cliente",
      "segmento": "evento",
      "vendedor": "Rafael",
      "pedidos": 3,
      "total": 18506,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2025-11-21"
    },
    {
      "id": "C0023",
      "nome": "Monte Alto Futebol Clube",
      "fantasia": "MONTE SPORTS",
      "tipo": "J",
      "documento": "16658760366909",
      "contato": "Tatiane",
      "telefone": "",
      "celular": "62978141096",
      "email": "montealto@exemplo.com.br",
      "endereco": "Rua 1006, 259",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Catalão",
      "uf": "GO",
      "cep": "75704650",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Rafael",
      "pedidos": 3,
      "total": 7985,
      "ultimoPedido": "2026-07-02",
      "criadoEm": "2024-04-25"
    },
    {
      "id": "C0024",
      "nome": "Flamboyant Distribuidora",
      "fantasia": "",
      "tipo": "J",
      "documento": "46706562729806",
      "contato": "Juliana",
      "telefone": "",
      "celular": "62992461444",
      "email": "flamboyant@exemplo.com.br",
      "endereco": "Rua João Pessoa, 999",
      "complemento": "",
      "bairro": "Setor Marista",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38475291",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-01-23"
    },
    {
      "id": "C0025",
      "nome": "Atlético Aurora",
      "fantasia": "ATLÉTICO SPORTS",
      "tipo": "J",
      "documento": "65375564641708",
      "contato": "Patrícia",
      "telefone": "6230137046",
      "celular": "62957334673",
      "email": "aurora@exemplo.com.br",
      "endereco": "Avenida Anhanguera, 1651",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74703423",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Henrique",
      "pedidos": 10,
      "total": 13048,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2026-06-10"
    },
    {
      "id": "C0026",
      "nome": "Uirapuru Engenharia",
      "fantasia": "UIRAPURU GROUP",
      "tipo": "J",
      "documento": "92327193745299",
      "contato": "Marcela",
      "telefone": "",
      "celular": "62926836096",
      "email": "uirapuru@exemplo.com.br",
      "endereco": "Avenida Goiás, 1162",
      "complemento": "Sala 18",
      "bairro": "Setor Campinas",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74866712",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Rafael",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-06-03"
    },
    {
      "id": "C0027",
      "nome": "Festival Buriti",
      "fantasia": "FESTIVAL EVENTOS",
      "tipo": "J",
      "documento": "31931491905865",
      "contato": "Eduardo",
      "telefone": "",
      "celular": "62982896590",
      "email": "buriti@exemplo.com.br",
      "endereco": "Avenida Anhanguera, 456",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74876842",
      "tipoDeContato": "Cliente",
      "segmento": "evento",
      "vendedor": "Marcela",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-04-23"
    },
    {
      "id": "C0028",
      "nome": "Comunidade Primavera",
      "fantasia": "",
      "tipo": "J",
      "documento": "26284987769453",
      "contato": "Aline",
      "telefone": "",
      "celular": "62945698385",
      "email": "primavera@exemplo.com.br",
      "endereco": "Rua 1006, 952",
      "complemento": "Galpão 3",
      "bairro": "Setor Campinas",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74868465",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Henrique",
      "pedidos": 1,
      "total": 5327,
      "ultimoPedido": "2026-04-15",
      "criadoEm": "2023-03-31"
    },
    {
      "id": "C0029",
      "nome": "Associação Tucano",
      "fantasia": "",
      "tipo": "F",
      "documento": "35454948083",
      "contato": "Aline",
      "telefone": "",
      "celular": "62939547658",
      "email": "tucano@exemplo.com.br",
      "endereco": "Rua 1006, 1331",
      "complemento": "Sala 36",
      "bairro": "Setor Campinas",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74863212",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 5,
      "total": 20877,
      "ultimoPedido": "2026-08-17",
      "criadoEm": "2023-12-30"
    },
    {
      "id": "C0030",
      "nome": "Instituto Educacional Pulse",
      "fantasia": "",
      "tipo": "J",
      "documento": "36349578856855",
      "contato": "Fernando",
      "telefone": "",
      "celular": "62944386023",
      "email": "pulse@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 1176",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Jataí",
      "uf": "GO",
      "cep": "75802330",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Rafael",
      "pedidos": 2,
      "total": 4520,
      "ultimoPedido": "2026-01-15",
      "criadoEm": "2025-08-02"
    },
    {
      "id": "C0031",
      "nome": "Cerrado Futebol Clube",
      "fantasia": "CERRADO SPORTS",
      "tipo": "J",
      "documento": "74989413435240",
      "contato": "Tatiane",
      "telefone": "",
      "celular": "62920735494",
      "email": "cerrado@exemplo.com.br",
      "endereco": "Avenida Anhanguera, 1763",
      "complemento": "",
      "bairro": "Jardim Goiás",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71792440",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Henrique",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-12"
    },
    {
      "id": "C0032",
      "nome": "Grupo Vertex",
      "fantasia": "",
      "tipo": "J",
      "documento": "77752047116719",
      "contato": "Diego",
      "telefone": "",
      "celular": "62924853444",
      "email": "vertex@exemplo.com.br",
      "endereco": "Avenida T-9, 697",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74268599",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 19,
      "total": 80194,
      "ultimoPedido": "2026-08-03",
      "criadoEm": "2026-03-10"
    },
    {
      "id": "C0033",
      "nome": "Metalúrgica Girassol",
      "fantasia": "",
      "tipo": "J",
      "documento": "67749649909133",
      "contato": "Marcela",
      "telefone": "6237171854",
      "celular": "62913303573",
      "email": "girassol@exemplo.com.br",
      "endereco": "Avenida Goiás, 1791",
      "complemento": "Sala 26",
      "bairro": "Setor Oeste",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75385289",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 1925,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2025-10-15"
    },
    {
      "id": "C0034",
      "nome": "Grupo Araguaia",
      "fantasia": "",
      "tipo": "F",
      "documento": "47134936183",
      "contato": "Renata",
      "telefone": "",
      "celular": "62943523330",
      "email": "araguaia@exemplo.com.br",
      "endereco": "Rua Padre Wendel, 120",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75007866",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Rafael",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-01"
    },
    {
      "id": "C0035",
      "nome": "Secretaria de Esportes de Pequi",
      "fantasia": "",
      "tipo": "J",
      "documento": "74648877190659",
      "contato": "Rogério",
      "telefone": "",
      "celular": "62904232496",
      "email": "pequi@exemplo.com.br",
      "endereco": "Avenida Goiás, 1862",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75386617",
      "tipoDeContato": "Cliente",
      "segmento": "orgao",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 6575,
      "ultimoPedido": "2025-07-19",
      "criadoEm": "2023-06-10"
    },
    {
      "id": "C0036",
      "nome": "Secretaria de Esportes de Rio Claro",
      "fantasia": "",
      "tipo": "J",
      "documento": "27874296717565",
      "contato": "Aline",
      "telefone": "",
      "celular": "62917133634",
      "email": "rioclaro@exemplo.com.br",
      "endereco": "Avenida Perimetral, 73",
      "complemento": "Quadra 30 lote 15",
      "bairro": "Setor Oeste",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75266031",
      "tipoDeContato": "Cliente",
      "segmento": "orgao",
      "vendedor": "Rafael",
      "pedidos": 3,
      "total": 9986,
      "ultimoPedido": "2026-06-16",
      "criadoEm": "2025-01-18"
    },
    {
      "id": "C0037",
      "nome": "Colégio Pequi",
      "fantasia": "",
      "tipo": "J",
      "documento": "54516808760385",
      "contato": "Renata",
      "telefone": "",
      "celular": "62981678242",
      "email": "pequi@exemplo.com.br",
      "endereco": "Rua 1006, 501",
      "complemento": "Galpão 3",
      "bairro": "Jardim Goiás",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38437215",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Marcela",
      "pedidos": 19,
      "total": 22885,
      "ultimoPedido": "2026-08-03",
      "criadoEm": "2023-08-03"
    },
    {
      "id": "C0038",
      "nome": "Cooperativa Primavera",
      "fantasia": "",
      "tipo": "J",
      "documento": "24808613171274",
      "contato": "Bruno",
      "telefone": "6236324872",
      "celular": "62944797807",
      "email": "primavera@exemplo.com.br",
      "endereco": "Avenida Contorno, 588",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71901092",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 27,
      "total": 101162,
      "ultimoPedido": "2026-06-16",
      "criadoEm": "2025-04-19"
    },
    {
      "id": "C0039",
      "nome": "Metalúrgica Sabiá",
      "fantasia": "METALÚRGICA GROUP",
      "tipo": "J",
      "documento": "82146584044997",
      "contato": "Juliana",
      "telefone": "6230296788",
      "celular": "62973169824",
      "email": "sabiá@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 589",
      "complemento": "",
      "bairro": "Cidade Jardim",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75081590",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 5,
      "total": 14681,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2023-08-15"
    },
    {
      "id": "C0040",
      "nome": "Monte Alto Distribuidora",
      "fantasia": "MONTE GROUP",
      "tipo": "J",
      "documento": "96360576627028",
      "contato": "Larissa",
      "telefone": "6232989547",
      "celular": "62954392644",
      "email": "montealto@exemplo.com.br",
      "endereco": "Avenida Independência, 511",
      "complemento": "",
      "bairro": "Jardim Goiás",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38413962",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Rafael",
      "pedidos": 27,
      "total": 158914,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2023-09-19"
    },
    {
      "id": "C0041",
      "nome": "Jatobá Futebol Clube",
      "fantasia": "",
      "tipo": "J",
      "documento": "17459615865780",
      "contato": "Vitor",
      "telefone": "6235975195",
      "celular": "62911214846",
      "email": "jatobá@exemplo.com.br",
      "endereco": "Rua 1006, 1473",
      "complemento": "Sala 7",
      "bairro": "Jardim América",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38445957",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Henrique",
      "pedidos": 10,
      "total": 49379,
      "ultimoPedido": "2026-08-03",
      "criadoEm": "2025-05-23"
    },
    {
      "id": "C0042",
      "nome": "Studio Pequi Fitness",
      "fantasia": "",
      "tipo": "J",
      "documento": "40050455623869",
      "contato": "Eduardo",
      "telefone": "6232164482",
      "celular": "62927853868",
      "email": "pequi@exemplo.com.br",
      "endereco": "Avenida Independência, 698",
      "complemento": "Galpão 4",
      "bairro": "Jardim Goiás",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75011777",
      "tipoDeContato": "Cliente",
      "segmento": "academia",
      "vendedor": "Rafael",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-04-01"
    },
    {
      "id": "C0043",
      "nome": "Metalúrgica Flamboyant",
      "fantasia": "METALÚRGICA GROUP",
      "tipo": "J",
      "documento": "23747407482175",
      "contato": "Diego",
      "telefone": "",
      "celular": "62949017951",
      "email": "flamboyant@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1602",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38474121",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Marcela",
      "pedidos": 14,
      "total": 33258,
      "ultimoPedido": "2025-07-19",
      "criadoEm": "2024-12-21"
    },
    {
      "id": "C0044",
      "nome": "Ipê Training Center",
      "fantasia": "",
      "tipo": "J",
      "documento": "95944064090974",
      "contato": "Aline",
      "telefone": "",
      "celular": "62999466772",
      "email": "ipe@exemplo.com.br",
      "endereco": "Rua das Acácias, 340",
      "complemento": "Quadra 4 lote 15",
      "bairro": "Parque Amazônia",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75854728",
      "tipoDeContato": "Cliente",
      "segmento": "academia",
      "vendedor": "Rafael",
      "pedidos": 1,
      "total": 4656,
      "ultimoPedido": "2026-04-15",
      "criadoEm": "2025-04-05"
    },
    {
      "id": "C0045",
      "nome": "Time Primavera",
      "fantasia": "TIME SPORTS",
      "tipo": "J",
      "documento": "04709521456232",
      "contato": "Camila",
      "telefone": "",
      "celular": "62959949697",
      "email": "primavera@exemplo.com.br",
      "endereco": "Rua 84, 469",
      "complemento": "Sala 18",
      "bairro": "Setor Bueno",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71038528",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "time",
      "vendedor": "Marcela",
      "pedidos": 6,
      "total": 37737,
      "ultimoPedido": "2025-07-19",
      "criadoEm": "2025-09-29"
    },
    {
      "id": "C0046",
      "nome": "Prefeitura de Boa Vista",
      "fantasia": "",
      "tipo": "J",
      "documento": "17123685160481",
      "contato": "Paulo",
      "telefone": "",
      "celular": "62960385295",
      "email": "boavista@exemplo.com.br",
      "endereco": "Avenida Independência, 1013",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Jataí",
      "uf": "GO",
      "cep": "75800841",
      "tipoDeContato": "Cliente",
      "segmento": "orgao",
      "vendedor": "Marcela",
      "pedidos": 8,
      "total": 25184,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2024-08-01"
    },
    {
      "id": "C0047",
      "nome": "Instituto Educacional Nova Era",
      "fantasia": "",
      "tipo": "J",
      "documento": "93174612004711",
      "contato": "Juliana",
      "telefone": "",
      "celular": "62988073222",
      "email": "novaera@exemplo.com.br",
      "endereco": "Avenida Independência, 1548",
      "complemento": "",
      "bairro": "Jardim Goiás",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75848525",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Rafael",
      "pedidos": 4,
      "total": 14305,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2023-08-21"
    },
    {
      "id": "C0048",
      "nome": "Associação Esportiva Guará",
      "fantasia": "ASSOCIAÇÃO SPORTS",
      "tipo": "J",
      "documento": "17964053773515",
      "contato": "Paulo",
      "telefone": "6232177935",
      "celular": "62958761992",
      "email": "guará@exemplo.com.br",
      "endereco": "Rua C-140, 497",
      "complemento": "Quadra 24 lote 2",
      "bairro": "Vila Nova",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71388853",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Rafael",
      "pedidos": 4,
      "total": 10110,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2024-02-12"
    },
    {
      "id": "C0049",
      "nome": "Instituto Educacional Aurora",
      "fantasia": "INSTITUTO EDU",
      "tipo": "J",
      "documento": "32931839335290",
      "contato": "Aline",
      "telefone": "6234453683",
      "celular": "62923703129",
      "email": "aurora@exemplo.com.br",
      "endereco": "Avenida Goiás, 1015",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75389336",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Henrique",
      "pedidos": 6,
      "total": 14273,
      "ultimoPedido": "2026-08-26",
      "criadoEm": "2026-01-18"
    },
    {
      "id": "C0050",
      "nome": "Escola Anhanguera",
      "fantasia": "ESCOLA EDU",
      "tipo": "J",
      "documento": "95024026811775",
      "contato": "Vitor",
      "telefone": "",
      "celular": "62997262786",
      "email": "anhanguera@exemplo.com.br",
      "endereco": "Rua das Acácias, 1431",
      "complemento": "Quadra 22 lote 11",
      "bairro": "Vila Nova",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71338750",
      "tipoDeContato": "Cliente, Funcionario",
      "segmento": "escola",
      "vendedor": "Rafael",
      "pedidos": 5,
      "total": 19363,
      "ultimoPedido": "2026-04-15",
      "criadoEm": "2026-06-04"
    },
    {
      "id": "C0051",
      "nome": "Guarda Municipal de Pequi",
      "fantasia": "",
      "tipo": "J",
      "documento": "00766177115921",
      "contato": "Camila",
      "telefone": "",
      "celular": "62945059984",
      "email": "pequi@exemplo.com.br",
      "endereco": "Avenida Perimetral, 858",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75004743",
      "tipoDeContato": "Cliente",
      "segmento": "orgao",
      "vendedor": "Rafael",
      "pedidos": 14,
      "total": 39460,
      "ultimoPedido": "2026-04-15",
      "criadoEm": "2023-09-10"
    },
    {
      "id": "C0052",
      "nome": "Festival Vertex",
      "fantasia": "",
      "tipo": "J",
      "documento": "18367365766156",
      "contato": "Paulo",
      "telefone": "",
      "celular": "62941767132",
      "email": "vertex@exemplo.com.br",
      "endereco": "Rua C-140, 1379",
      "complemento": "Sala 35",
      "bairro": "Setor Oeste",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75269575",
      "tipoDeContato": "Cliente",
      "segmento": "evento",
      "vendedor": "Henrique",
      "pedidos": 1,
      "total": 4952,
      "ultimoPedido": "2026-06-16",
      "criadoEm": "2026-04-16"
    },
    {
      "id": "C0053",
      "nome": "Circuito Boa Vista",
      "fantasia": "",
      "tipo": "J",
      "documento": "28098851656049",
      "contato": "Bruno",
      "telefone": "",
      "celular": "62957612697",
      "email": "boavista@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1097",
      "complemento": "Quadra 16 lote 7",
      "bairro": "Jardim Goiás",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75385131",
      "tipoDeContato": "Cliente",
      "segmento": "evento",
      "vendedor": "Henrique",
      "pedidos": 8,
      "total": 31149,
      "ultimoPedido": "2026-08-26",
      "criadoEm": "2022-12-26"
    },
    {
      "id": "C0054",
      "nome": "Paróquia Tucano",
      "fantasia": "",
      "tipo": "J",
      "documento": "51493689980940",
      "contato": "Rogério",
      "telefone": "",
      "celular": "62944776062",
      "email": "tucano@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1372",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75037353",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Henrique",
      "pedidos": 3,
      "total": 8913,
      "ultimoPedido": "2026-08-26",
      "criadoEm": "2025-11-11"
    },
    {
      "id": "C0055",
      "nome": "Time Boa Vista",
      "fantasia": "",
      "tipo": "J",
      "documento": "18366752545991",
      "contato": "Camila",
      "telefone": "",
      "celular": "62925493579",
      "email": "boavista@exemplo.com.br",
      "endereco": "Avenida Contorno, 1699",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74799075",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Marcela",
      "pedidos": 19,
      "total": 86359,
      "ultimoPedido": "2026-03-06",
      "criadoEm": "2026-03-17"
    },
    {
      "id": "C0056",
      "nome": "Associação Nova Era",
      "fantasia": "",
      "tipo": "J",
      "documento": "38156149784036",
      "contato": "Patrícia",
      "telefone": "",
      "celular": "62908971125",
      "email": "novaera@exemplo.com.br",
      "endereco": "Avenida Anhanguera, 1827",
      "complemento": "Sala 28",
      "bairro": "Centro",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38411637",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "Marcela",
      "pedidos": 1,
      "total": 2678,
      "ultimoPedido": "2026-08-17",
      "criadoEm": "2025-11-23"
    },
    {
      "id": "C0057",
      "nome": "Delta Training Center",
      "fantasia": "",
      "tipo": "J",
      "documento": "62268388516060",
      "contato": "Juliana",
      "telefone": "",
      "celular": "62912756129",
      "email": "delta@exemplo.com.br",
      "endereco": "Avenida Goiás, 516",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Jataí",
      "uf": "GO",
      "cep": "75802651",
      "tipoDeContato": "Cliente",
      "segmento": "academia",
      "vendedor": "Marcela",
      "pedidos": 8,
      "total": 27462,
      "ultimoPedido": "2026-07-02",
      "criadoEm": "2023-01-28"
    },
    {
      "id": "C0058",
      "nome": "Escola Serra Dourada",
      "fantasia": "",
      "tipo": "J",
      "documento": "97516136968164",
      "contato": "Paulo",
      "telefone": "",
      "celular": "62936306456",
      "email": "serradourada@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 1387",
      "complemento": "Quadra 23 lote 1",
      "bairro": "Setor Oeste",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75266761",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Henrique",
      "pedidos": 19,
      "total": 35947,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2023-02-12"
    },
    {
      "id": "C0059",
      "nome": "Paróquia Anhanguera",
      "fantasia": "",
      "tipo": "J",
      "documento": "23124329212779",
      "contato": "Bruno",
      "telefone": "6233679059",
      "celular": "62973546295",
      "email": "anhanguera@exemplo.com.br",
      "endereco": "Avenida Independência, 485",
      "complemento": "Galpão 6",
      "bairro": "Centro",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38422202",
      "tipoDeContato": "Cliente",
      "segmento": "igreja",
      "vendedor": "Marcela",
      "pedidos": 27,
      "total": 178976,
      "ultimoPedido": "2026-07-19",
      "criadoEm": "2025-10-26"
    },
    {
      "id": "C0060",
      "nome": "Prefeitura de Jacarandá",
      "fantasia": "",
      "tipo": "J",
      "documento": "90581477005411",
      "contato": "Bruno",
      "telefone": "6232114115",
      "celular": "62997339307",
      "email": "jacarandá@exemplo.com.br",
      "endereco": "Rua C-140, 61",
      "complemento": "Sala 6",
      "bairro": "Parque Amazônia",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38497299",
      "tipoDeContato": "Cliente",
      "segmento": "orgao",
      "vendedor": "Rafael",
      "pedidos": 4,
      "total": 14519,
      "ultimoPedido": "2026-05-15",
      "criadoEm": "2026-06-08"
    },
    {
      "id": "C0061",
      "nome": "Metalúrgica Serra Dourada",
      "fantasia": "",
      "tipo": "J",
      "documento": "78207151820377",
      "contato": "Juliana",
      "telefone": "6236117009",
      "celular": "62985643600",
      "email": "serradourada@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 1227",
      "complemento": "Galpão 6",
      "bairro": "Centro",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "71752882",
      "tipoDeContato": "Cliente",
      "segmento": "empresa",
      "vendedor": "Rafael",
      "pedidos": 3,
      "total": 9299,
      "ultimoPedido": "2026-08-03",
      "criadoEm": "2024-06-29"
    },
    {
      "id": "C0062",
      "nome": "Instituto Educacional Jacarandá",
      "fantasia": "",
      "tipo": "J",
      "documento": "15186449251925",
      "contato": "Tatiane",
      "telefone": "6232183859",
      "celular": "62964213112",
      "email": "jacarandá@exemplo.com.br",
      "endereco": "Avenida Perimetral, 1719",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75380018",
      "tipoDeContato": "Cliente",
      "segmento": "escola",
      "vendedor": "Marcela",
      "pedidos": 8,
      "total": 40656,
      "ultimoPedido": "2026-09-03",
      "criadoEm": "2024-12-05"
    },
    {
      "id": "C0063",
      "nome": "Time São Jorge",
      "fantasia": "TIME SPORTS",
      "tipo": "J",
      "documento": "68505423573322",
      "contato": "Marcela",
      "telefone": "",
      "celular": "62948462657",
      "email": "saojorge@exemplo.com.br",
      "endereco": "Avenida T-9, 1194",
      "complemento": "",
      "bairro": "Jardim América",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74826330",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Rafael",
      "pedidos": 6,
      "total": 32688,
      "ultimoPedido": "2025-07-19",
      "criadoEm": "2023-09-18"
    },
    {
      "id": "C0064",
      "nome": "Associação Esportiva Nova Era",
      "fantasia": "",
      "tipo": "J",
      "documento": "22292706537947",
      "contato": "Larissa",
      "telefone": "6236663471",
      "celular": "62987494918",
      "email": "novaera@exemplo.com.br",
      "endereco": "Avenida Goiás, 1679",
      "complemento": "Galpão 4",
      "bairro": "Setor Campinas",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75843483",
      "tipoDeContato": "Cliente",
      "segmento": "time",
      "vendedor": "Marcela",
      "pedidos": 2,
      "total": 13194,
      "ultimoPedido": "2025-11-06",
      "criadoEm": "2024-01-14"
    },
    {
      "id": "C0065",
      "nome": "Daniella Ferreira da Silva",
      "fantasia": "",
      "tipo": "F",
      "documento": "68332670570",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-04"
    },
    {
      "id": "C0066",
      "nome": "Raul Moraes Duarte",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua das Acácias, 608",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77792513",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-04-07"
    },
    {
      "id": "C0067",
      "nome": "Leticia Jumpers",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62966677958",
      "email": "",
      "endereco": "Avenida Contorno, 525",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75680333",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-11-18"
    },
    {
      "id": "C0068",
      "nome": "Hugo PCDF",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62999364802",
      "email": "",
      "endereco": "Avenida Rio Verde, 230",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "São Paulo",
      "uf": "SP",
      "cep": "01721389",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-09-11"
    },
    {
      "id": "C0069",
      "nome": "Gabriele Rancho Alegre",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-07-10"
    },
    {
      "id": "C0070",
      "nome": "Diogo Sousa",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62935918395",
      "email": "diogo66@exemplo.com.br",
      "endereco": "Rua João Pessoa, 1573",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75288905",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-10-14"
    },
    {
      "id": "C0071",
      "nome": "Davi House Cell",
      "fantasia": "",
      "tipo": "F",
      "documento": "00960955976",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-06-07"
    },
    {
      "id": "C0072",
      "nome": "Breno Brasiel",
      "fantasia": "",
      "tipo": "F",
      "documento": "66703165295",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-28"
    },
    {
      "id": "C0073",
      "nome": "Iuri Muri Marianni",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua das Acácias, 618",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77504800",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-04-26"
    },
    {
      "id": "C0074",
      "nome": "Corrida 5km Eixao",
      "fantasia": "",
      "tipo": "F",
      "documento": "26857516088",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-07"
    },
    {
      "id": "C0075",
      "nome": "Drogaria Viver Bem",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-08-08"
    },
    {
      "id": "C0076",
      "nome": "Maro",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-01-05"
    },
    {
      "id": "C0077",
      "nome": "Rani",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62986554025",
      "email": "rani22@exemplo.com.br",
      "endereco": "Avenida Contorno, 1651",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75818953",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-07-10"
    },
    {
      "id": "C0078",
      "nome": "Leticia Jumpers Artesanal",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62924847238",
      "email": "leticia57@exemplo.com.br",
      "endereco": "Avenida Goiás, 1780",
      "complemento": "",
      "bairro": "Setor Marista",
      "cidade": "Aparecida de Goiânia",
      "uf": "GO",
      "cep": "74615309",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-04"
    },
    {
      "id": "C0079",
      "nome": "Jose Henrique Cardoso Caetano",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62977499223",
      "email": "",
      "endereco": "Rua das Acácias, 1080",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "70567514",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-12-21"
    },
    {
      "id": "C0080",
      "nome": "Matheus Fernandes",
      "fantasia": "",
      "tipo": "F",
      "documento": "78122366482",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-02-08"
    },
    {
      "id": "C0081",
      "nome": "Bruna Aparecida Lopes",
      "fantasia": "",
      "tipo": "F",
      "documento": "48455865217",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-03-07"
    },
    {
      "id": "C0082",
      "nome": "Carlos Eduardo Nunes",
      "fantasia": "",
      "tipo": "F",
      "documento": "57296610021",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-05-23"
    },
    {
      "id": "C0083",
      "nome": "Sabrina Ribeiro Alves",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-08"
    },
    {
      "id": "C0084",
      "nome": "Wesley Antonio Rocha",
      "fantasia": "",
      "tipo": "F",
      "documento": "20714960591",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-08-05"
    },
    {
      "id": "C0085",
      "nome": "Talita Menezes",
      "fantasia": "",
      "tipo": "F",
      "documento": "90183383507",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-01-09"
    },
    {
      "id": "C0086",
      "nome": "Pedro Ivo Tavares",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62996811352",
      "email": "",
      "endereco": "Rua Padre Wendel, 1125",
      "complemento": "",
      "bairro": "Cidade Jardim",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75675369",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-09-20"
    },
    {
      "id": "C0087",
      "nome": "Juliana Prado",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62970822589",
      "email": "juliana88@exemplo.com.br",
      "endereco": "Rua 1006, 774",
      "complemento": "",
      "bairro": "Parque Amazônia",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "70294063",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-07-01"
    },
    {
      "id": "C0088",
      "nome": "Anderson Vilela",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua João Pessoa, 183",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77674527",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-02-23"
    },
    {
      "id": "C0089",
      "nome": "Nayara Campos",
      "fantasia": "",
      "tipo": "F",
      "documento": "89554463642",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-06-06"
    },
    {
      "id": "C0090",
      "nome": "Otavio Bastos",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Avenida Contorno, 1869",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77119765",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-24"
    },
    {
      "id": "C0091",
      "nome": "Rita de Cassia Melo",
      "fantasia": "",
      "tipo": "F",
      "documento": "42652238237",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-02-20"
    },
    {
      "id": "C0092",
      "nome": "Gustavo Henrique Pires",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-23"
    },
    {
      "id": "C0093",
      "nome": "Larissa Fontes",
      "fantasia": "",
      "tipo": "F",
      "documento": "94767664941",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-08-07"
    },
    {
      "id": "C0094",
      "nome": "Marcos Vinicius Abreu",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Avenida T-9, 600",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "70461170",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-09-06"
    },
    {
      "id": "C0095",
      "nome": "Camila Rezende",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua das Acácias, 1579",
      "complemento": "",
      "bairro": "Jardim América",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "70269956",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-24"
    },
    {
      "id": "C0096",
      "nome": "Fernando Bueno Leite",
      "fantasia": "",
      "tipo": "F",
      "documento": "06385158774",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-10-25"
    },
    {
      "id": "C0097",
      "nome": "Priscila Antunes",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62992807694",
      "email": "priscila19@exemplo.com.br",
      "endereco": "Rua 84, 1048",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75113082",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-28"
    },
    {
      "id": "C0098",
      "nome": "Vitor Hugo Salles",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua João Pessoa, 855",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77740876",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-02-07"
    },
    {
      "id": "C0099",
      "nome": "Elaine Cristina Dorneles",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-10"
    },
    {
      "id": "C0100",
      "nome": "Rodrigo Peixoto",
      "fantasia": "",
      "tipo": "F",
      "documento": "36310647908",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-18"
    },
    {
      "id": "C0101",
      "nome": "Simone Andrade",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62904557017",
      "email": "simone80@exemplo.com.br",
      "endereco": "Avenida T-9, 977",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Brasília",
      "uf": "DF",
      "cep": "70261617",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-08"
    },
    {
      "id": "C0102",
      "nome": "Thiago Barcelos",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-21"
    },
    {
      "id": "C0103",
      "nome": "Amanda Queiroz",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-03-27"
    },
    {
      "id": "C0104",
      "nome": "Lucas Naves",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-02-04"
    },
    {
      "id": "C0105",
      "nome": "Patricia Gouveia",
      "fantasia": "",
      "tipo": "F",
      "documento": "26342406887",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-01-27"
    },
    {
      "id": "C0106",
      "nome": "Rafael Siqueira Borba",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Avenida T-9, 1281",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77548659",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-09-22"
    },
    {
      "id": "C0107",
      "nome": "Isabela Moura",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Rua Padre Wendel, 340",
      "complemento": "",
      "bairro": "Setor Marista",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75799407",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-01-23"
    },
    {
      "id": "C0108",
      "nome": "Joao Vitor Assuncao",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62953242012",
      "email": "joao31@exemplo.com.br",
      "endereco": "Avenida Goiás, 763",
      "complemento": "",
      "bairro": "Setor Bueno",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75659597",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-02-02"
    },
    {
      "id": "C0109",
      "nome": "Kelly Cristina Faria",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-02"
    },
    {
      "id": "C0110",
      "nome": "Alexandre Ramos Pinto",
      "fantasia": "",
      "tipo": "F",
      "documento": "72208755059",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-06-12"
    },
    {
      "id": "C0111",
      "nome": "Vanessa Teles",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Avenida T-9, 1185",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74965744",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-02-02"
    },
    {
      "id": "C0112",
      "nome": "Igor Mendanha",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62973356661",
      "email": "igor98@exemplo.com.br",
      "endereco": "Avenida Rio Verde, 780",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74280852",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-11-05"
    },
    {
      "id": "C0113",
      "nome": "Renata Cardoso Lima",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "Avenida Contorno, 1636",
      "complemento": "",
      "bairro": "Cidade Jardim",
      "cidade": "Anápolis",
      "uf": "GO",
      "cep": "75779592",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-28"
    },
    {
      "id": "C0114",
      "nome": "Bruno Falcao",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62905206843",
      "email": "bruno86@exemplo.com.br",
      "endereco": "Avenida Anhanguera, 337",
      "complemento": "",
      "bairro": "Jardim América",
      "cidade": "São Paulo",
      "uf": "SP",
      "cep": "01244558",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-12"
    },
    {
      "id": "C0115",
      "nome": "Tatiane Machado",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62964823328",
      "email": "",
      "endereco": "Avenida Perimetral, 1878",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Goiânia",
      "uf": "GO",
      "cep": "74804936",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-09-21"
    },
    {
      "id": "C0116",
      "nome": "Everton Luiz Camargo",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62931708382",
      "email": "",
      "endereco": "Rua C-140, 496",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75838335",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-27"
    },
    {
      "id": "C0117",
      "nome": "Bianca Nogueira",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-07-04"
    },
    {
      "id": "C0118",
      "nome": "Samuel Arantes",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-05-23"
    },
    {
      "id": "C0119",
      "nome": "Michele Ferraz",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-21"
    },
    {
      "id": "C0120",
      "nome": "Diego Portilho",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62981881636",
      "email": "",
      "endereco": "Avenida Anhanguera, 880",
      "complemento": "",
      "bairro": "Vila Nova",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38201169",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-05-22"
    },
    {
      "id": "C0121",
      "nome": "Aline Barbosa Cunha",
      "fantasia": "",
      "tipo": "F",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62954573161",
      "email": "aline39@exemplo.com.br",
      "endereco": "Rua das Acácias, 950",
      "complemento": "",
      "bairro": "Setor Oeste",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75680058",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-02-10"
    },
    {
      "id": "C0122",
      "nome": "Ricardo Amorim",
      "fantasia": "",
      "tipo": "F",
      "documento": "70036920733",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2022-04-09"
    },
    {
      "id": "C0123",
      "nome": "Jessica Beltrao",
      "fantasia": "",
      "tipo": "F",
      "documento": "28920949278",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-06-13"
    },
    {
      "id": "C0124",
      "nome": "Murilo Tanaka",
      "fantasia": "",
      "tipo": "F",
      "documento": "96695464271",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-16"
    },
    {
      "id": "C0125",
      "nome": "ZAIDY SHEIKH PERFORMANCE",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-08-25"
    },
    {
      "id": "C0126",
      "nome": "G DA SILVA MOURA INOVA COMERCIO LTDA",
      "fantasia": "INOVA",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-12-22"
    },
    {
      "id": "C0127",
      "nome": "SUPERMERCADO BOM PRECO",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-03-15"
    },
    {
      "id": "C0128",
      "nome": "STUDIO PILATES FLOR",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62950577454",
      "email": "",
      "endereco": "Avenida Independência, 570",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Rio Verde",
      "uf": "GO",
      "cep": "75957741",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2025-06-20"
    },
    {
      "id": "C0129",
      "nome": "MULTI SERVICE MANUTENCAO LTDA",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62969024133",
      "email": "multi88@exemplo.com.br",
      "endereco": "Rua 84, 64",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Trindade",
      "uf": "GO",
      "cep": "75753883",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-02-27"
    },
    {
      "id": "C0130",
      "nome": "ATACADO CENTRO OESTE LTDA",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-03"
    },
    {
      "id": "C0131",
      "nome": "PANIFICADORA PAO DO CERRADO",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62962737671",
      "email": "",
      "endereco": "Rua 84, 658",
      "complemento": "",
      "bairro": "Setor Sul",
      "cidade": "Senador Canedo",
      "uf": "GO",
      "cep": "75585717",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-01-19"
    },
    {
      "id": "C0132",
      "nome": "AUTO PECAS ARAGUAIA LTDA",
      "fantasia": "",
      "tipo": "J",
      "documento": "39272448555390",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2024-01-15"
    },
    {
      "id": "C0133",
      "nome": "CLINICA VIDA PLENA",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62965622173",
      "email": "clinica44@exemplo.com.br",
      "endereco": "Avenida Goiás, 1639",
      "complemento": "",
      "bairro": "Centro",
      "cidade": "Uberlândia",
      "uf": "MG",
      "cep": "38527960",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-04-06"
    },
    {
      "id": "C0134",
      "nome": "TRANSPORTES PLANALTO LTDA",
      "fantasia": "",
      "tipo": "J",
      "documento": "65964300072953",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-07-07"
    },
    {
      "id": "C0135",
      "nome": "CONFECCOES BELA VISTA",
      "fantasia": "",
      "tipo": "J",
      "documento": "",
      "contato": "",
      "telefone": "",
      "celular": "62966298217",
      "email": "",
      "endereco": "Rua C-140, 1241",
      "complemento": "",
      "bairro": "Setor Campinas",
      "cidade": "Palmas",
      "uf": "TO",
      "cep": "77937605",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2023-11-07"
    },
    {
      "id": "C0136",
      "nome": "GRAFICA RAPIDA CENTRAL",
      "fantasia": "",
      "tipo": "J",
      "documento": "72792452771872",
      "contato": "",
      "telefone": "",
      "celular": "",
      "email": "",
      "endereco": "",
      "complemento": "",
      "bairro": "",
      "cidade": "",
      "uf": "",
      "cep": "",
      "tipoDeContato": "Cliente",
      "segmento": "outros",
      "vendedor": "",
      "pedidos": 0,
      "total": 0,
      "ultimoPedido": "",
      "criadoEm": "2026-06-02"
    }
  ] as Cliente[]

/** true enquanto a lista for de exemplo. A tela avisa quem esta olhando. */
export const DADO_DE_EXEMPLO = true

/* A lista viva. Salvar mexe aqui, e nao no banco, porque banco ainda nao ha.
   O que for cadastrado ou editado vale enquanto a aba estiver aberta, e some
   ao recarregar. A tela diz isso. */
let base: Cliente[] = [...EXEMPLO]

export function listarClientes(): Cliente[] {
  return base
}

export function acharCliente(id: string): Cliente | undefined {
  return base.find((c) => c.id === id)
}

/** Salva um cliente novo ou altera um que ja existe, e devolve o que ficou. */
export function salvarCliente(c: Cliente): Cliente {
  const i = base.findIndex((x) => x.id === c.id)
  if (i >= 0) {
    base = base.map((x, j) => (j === i ? c : x))
    return c
  }
  const novo = { ...c, id: c.id || proximoId() }
  base = [novo, ...base]
  return novo
}

function proximoId() {
  const maior = base.reduce((m, c) => Math.max(m, Number(c.id.replace(/\D/g, '')) || 0), 0)
  return 'C' + String(maior + 1).padStart(4, '0')
}

/** O molde de um cliente que ainda nao existe. */
export function clienteEmBranco(): Cliente {
  return {
    id: '',
    nome: '',
    fantasia: '',
    tipo: 'F',
    documento: '',
    contato: '',
    telefone: '',
    celular: '',
    email: '',
    endereco: '',
    complemento: '',
    bairro: '',
    cidade: '',
    uf: 'GO',
    cep: '',
    tipoDeContato: 'Cliente',
    segmento: 'outros',
    vendedor: '',
    pedidos: 0,
    total: 0,
    ultimoPedido: '',
    criadoEm: new Date().toISOString().slice(0, 10),
  }
}
